services:
  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    container_name: flask_app
#    entrypoint: sh
#    stdin_open: true
#    tty: true
    ports:
      - "5100:5100"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./flask_app:/shared/flask_app

  daemon:
    build: ./daemon
    container_name: daemon_service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./flask_app:/shared/flask_app
    working_dir: /app

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./init_scripts/create_sequence.sql:/docker-entrypoint-initdb.d/db.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  pgdata:
